#############################################################################
# Makefile for building: SRVjoy
# Generated by qmake (2.01a) (Qt 4.5.0) on: Wed Nov 4 16:49:46 2009
# Project:  Surveyor_GUI.pro
# Template: app
# Command: /opt/qtsdk-2009.01/qt/bin/qmake -unix -o Makefile Surveyor_GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.01/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.01/qt/include/QtCore -I/opt/qtsdk-2009.01/qt/include/QtGui -I/opt/qtsdk-2009.01/qt/include -I/usr/local/include/player-2.1/ -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qtsdk-2009.01/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.01/qt/lib -L/usr/local/lib -lplayerc++ -lQtGui -L/opt/qtsdk-2009.01/qt/lib -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.01/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ImageThread.cpp \
		SRVjoy.cpp \
		args.cpp \
		main.cpp moc_SRVjoy.cpp \
		qrc_playerGUI.cpp
OBJECTS       = ImageThread.o \
		SRVjoy.o \
		args.o \
		main.o \
		moc_SRVjoy.o \
		qrc_playerGUI.o
DIST          = /opt/qtsdk-2009.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/lex.prf \
		Surveyor_GUI.pro
QMAKE_TARGET  = SRVjoy
DESTDIR       = 
TARGET        = SRVjoy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Surveyor_GUI.pro  /opt/qtsdk-2009.01/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.01/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.01/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.01/qt/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Surveyor_GUI.pro
/opt/qtsdk-2009.01/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.01/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.01/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.01/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.01/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/release.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.01/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.01/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.01/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Surveyor_GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SRVjoy1.0.0 || $(MKDIR) .tmp/SRVjoy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SRVjoy1.0.0/ && $(COPY_FILE) --parents args.h SRVjoy.h .tmp/SRVjoy1.0.0/ && $(COPY_FILE) --parents playerGUI.qrc .tmp/SRVjoy1.0.0/ && $(COPY_FILE) --parents ImageThread.cpp SRVjoy.cpp args.cpp main.cpp .tmp/SRVjoy1.0.0/ && (cd `dirname .tmp/SRVjoy1.0.0` && $(TAR) SRVjoy1.0.0.tar SRVjoy1.0.0 && $(COMPRESS) SRVjoy1.0.0.tar) && $(MOVE) `dirname .tmp/SRVjoy1.0.0`/SRVjoy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SRVjoy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_SRVjoy.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SRVjoy.cpp
moc_SRVjoy.cpp: args.h \
		SRVjoy.h
	/opt/qtsdk-2009.01/qt/bin/moc $(DEFINES) $(INCPATH) SRVjoy.h -o moc_SRVjoy.cpp

compiler_rcc_make_all: qrc_playerGUI.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_playerGUI.cpp
qrc_playerGUI.cpp: playerGUI.qrc \
		images/player_button_v3.png \
		images/buttons/fwdleft.png \
		images/buttons/forward.png \
		images/buttons/fwdright.png \
		images/buttons/backleft.png \
		images/buttons/ccw.png \
		images/buttons/cw.png \
		images/buttons/camera-photo.png \
		images/buttons/backright.png \
		images/buttons/backward.png
	/opt/qtsdk-2009.01/qt/bin/rcc -name playerGUI playerGUI.qrc -o qrc_playerGUI.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

ImageThread.o: ImageThread.cpp SRVjoy.h \
		args.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageThread.o ImageThread.cpp

SRVjoy.o: SRVjoy.cpp SRVjoy.h \
		args.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SRVjoy.o SRVjoy.cpp

args.o: args.cpp args.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o args.o args.cpp

main.o: main.cpp SRVjoy.h \
		args.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_SRVjoy.o: moc_SRVjoy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SRVjoy.o moc_SRVjoy.cpp

qrc_playerGUI.o: qrc_playerGUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_playerGUI.o qrc_playerGUI.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

